[phases.setup]
nixPkgs = ["dotnet-sdk_10"]
nixpkgsArchive = "nixos-unstable"

[phases.install]
cmds = ["dotnet restore InformeObras.csproj"]

[phases.build]
cmds = ["dotnet publish InformeObras.csproj -c Release -o out"]

[start]
cmd = "dotnet out/InformeObras.dll"

[variables]
ASPNETCORE_URLS = "http://0.0.0.0:8080"
PORT = "8080"