# Configuración de Nixpacks para el Frontend SvelteKit (Static)

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

# Usamos el proveedor estático de Nixpacks para servir la carpeta 'build'
# Esto es más eficiente que usar 'npx serve'
[static]
directory = "build"
