# Configuración de Nixpacks para el Frontend SvelteKit (Static)

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

# Usamos npx serve para servir la carpeta 'build' en el puerto 80
[start]
cmd = "npx serve -s build -l 80"

[variables]
NODE_ENV = "production"
